name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_PUBLIC_SERVER_DOMAIN: ${{secrets.SERVER_DOMAIN}}
      NEXT_PUBLIC_IMGS_DOMAIN: ${{secrets.IMGS_DOMAIN}}
      NEXT_PUBLIC_WS_SERVER: ${{secrets.WS_SERVER}}
      SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
      SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${{secrets.MAPBOX_API_KEY}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm dedupe
    - run: npm run build --if-present

    - name: Change Directory
      run: cd /home/frandendstartawsil/actions-runner/_work/frontend/frontend
    - run: pm2 reload 0 
